ongAdocao/adocao/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('listaAnimais/',views.listaAnimais,name='listaAnimais'),
    path('teste/<int:idAnimal>',views.teste,name='teste'),

]

ongAdocao/ongAdocao/urls.py
from django.contrib import admin
from django.urls import path, include
from adocao import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adocao.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ongAdocao/adocao/models.py
from django.db import models
from django.contrib import admin
from django.utils.timezone import now
from django.contrib.auth.models import User

class Animal(models.Model):
    imagemAnimal = models.ImageField(upload_to='images/')
    descricao = models.CharField(
        max_length=255, null=False, blank=False
    )
    nomeAnimal = models.CharField(
        max_length=255, null=False, blank=False
    )
    adotado = models.BooleanField(default=False)
    macho = 1
    femea = 2
    gato = 3
    cachorro = 4
    pequeno = 5
    medio = 6
    grande = 7
    naoInformado = 8
    escolhasS = (
        (1, 'Macho'),
        (2, 'Femea'),
        (8, 'Nao informado')
    )
    escolhasR = (
        (3, 'Gato'),
        (4, 'Cachorro'),
        (8, 'Nao informado')
    )
    escolhasP = (
        (5, 'Pequeno'),
        (6, 'Medio'),
        (7, 'Grande'),
        (8, 'Nao informado')
    )
    sexo = models.IntegerField(choices=escolhasS, default=8)
    especie = models.IntegerField(choices=escolhasR, default=8)
    porte = models.IntegerField(choices=escolhasP, default=8)

    def __str__(self):
        return f"{self.nomeAnimal} ({self.descricao})"

    class Meta:
        verbose_name_plural = 'animais'

    class Meta:
       ordering = ['nomeAnimal']

class Pessoa(models.Model):
    nomePessoa = models.CharField(
        max_length=255, null=False, blank=False
    )
    telefonePessoa = models.CharField(
        max_length=30, null=False, blank=False
    )
    cpfPessoa = models.CharField(
        max_length=11, null=False, blank=False
    )
    enderecoPessoa= models.CharField(
        max_length=255, null=False, blank=False
    )

    def __str__(self):
        return self.nomePessoa

class Adocao(models.Model):
    data_adocao =  models.DateTimeField(default=now, editable=False)
    animal = models.ForeignKey(Animal,on_delete=models.CASCADE)
    pessoa = models.ForeignKey(Pessoa,on_delete=models.CASCADE)
    funcionario = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.animal.nomeAnimal

    class Meta:
        verbose_name_plural = 'adoções'

ongAdocao/adocao/views.py
from django.shortcuts import render
from .models import Animal
from django.core.paginator import Paginator



def listaAnimais(request):
    listaAnimais = Animal.objects.filter(adotado=False)
    return render(request, 'listaAnimais.html',{'animais':listaAnimais})

def teste(request,idAnimal):
    animal = Animal.objects.get(id=idAnimal)
    return render(request, 'descricao.html',{'animal':animal})


def index(request):
	animais = Animal.objects.filter(adotado=False)
	adotados = Animal.objects.filter(adotado=True)[:4]
	paginator = Paginator(animais, 8)
	page = request.GET.get('page')
	posts = paginator.get_page(page)
	return render(request, 'index.html',{'animais':posts,'animaisAdotados':adotados})

ongAdocao/adocao/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="shortcut icon" href="{% static 'images/ongadocao-favicon.ico'%}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <title> OngAdoção</title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container ">
        <a class="navbar-brand" href="{% url 'index' %}">Ong Adoção</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Início <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Quero ajudar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'listaAnimais' %}">Adotar</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>
  {% block bloco %}
  {% endblock %}
  </main>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>
</html>

ongAdocao/adocao/templates/descricao.html
{% extends 'base.html' %}
{% block bloco %}
<div class="container d-flex py-5 corDiv">
    <div class="d-flex justify-content-center  ">
        <img class="img-fuid" style="max-height:500px;" src="{{animal.imagemAnimal.url}}" class="img-thumbnail">
    </div>
    <div class="d-flex flex-column text-center;">
        <h3>{{animal.nomeAnimal}}</h3>
        <p class="card_text">{{animal.get_sexo_display}}</p>
        <p class="card_text">{{animal.get_porte_display}}</p>
    </div>
    <div class="justify-content-center">
        <button class="btn botao btn-outline-warning" type="submit">Adotar</button>
    </div>
    
</div>

{% endblock %}

ongAdocao/adocao/templates/index.html
{% extends 'base.html' %}

{% block bloco %}
    <div class="teste">
        <div class="container">
            <p>Nossos peludos estão ansiosos à espera de um lar!</p>
            <a href="#" class="btn-ajudar">Quero ajudar</a>
            <a href="#" class="btn-adotar">Adotar</a>
        </div>
    </div>
    <div class="container">
        {% if animais %}
        <h1 class="pt-4">Animais para adoção</h1>
        <ul class="cards">
            {% for Animal in animais %}
                <li class="cards_item"> 
                    <div class="card">
                        {% if Animal.adotado%}
                            <div class="ribbon-wrapper">
                                <div class="ribbon">Adotado</div>
                            </div>
                        {% endif %}
                        <div class="card_image">
                            <a href="{% url 'teste' Animal.id %}">
                                <img src="{{Animal.imagemAnimal.url}}" class="img-thumbnail">
                            </a>           
                        </div>
                        <div class="card_content">
                            <h2 class="card_title">{{Animal.nomeAnimal}}</h2>
                            <p class="card_text">{{Animal.get_sexo_display}}</p>
                            <p class="card_text">{{Animal.get_porte_display}}</p>
                            <a href="{% url 'teste' Animal.id %}">
                                <div class="botao">
                                    <button class="btn card_btn">Ver Mais</button>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Não há animais para a adoção </p>
        {% endif %}
    </div>
     <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if animais.has_previous %}
            <li class="page-ite">
                <a class="page-link" href="?page=1">Primeira</a>
            </li>
            
            <li class="page-item"><a class="page-link" href="?page={{ animais.previous_page_number }}">Anterior</a></li>
            
            {% endif %}
            {% if animais.has_next %}
            <li class="page-item active " aria-current="page">
                <a class="page-link" href="?page={{ animais.next_page_number }}">2  <span class="sr-only">(current)</span></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ animais.paginator.num_pages }}">Ultima</a>
            </li>
            {% endif %}
        </ul>
        </nav>
    </div> 
    <div class="container">
        <h1>Últimas adoções regisradas</h1>
        {% if animaisAdotados %}
        <ul class="cards">
            {% for Animal in animaisAdotados %}
                <li class="cards_item"> 
                    <div class="card">
                        {% if Animal.adotado%}
                            <div class="ribbon-wrapper">
                                <div class="ribbon">Adotado</div>
                            </div>
                        {% endif %}
                        <div class="card_image">
                            <a href="{% url 'teste' Animal.id %}">
                                <img src="{{Animal.imagemAnimal.url}}" class="img-thumbnail">
                            </a>           
                        </div>
                        <div class="card_content">
                            <h2 class="card_title">{{Animal.nomeAnimal}}</h2>
                            <p class="card_text">{{Animal.get_sexo_display}}</p>
                            <p class="card_text">{{Animal.get_porte_display}}</p>
                            <a href="{% url 'teste' Animal.id %}">
                                <div class="botao">
                                    <button class="btn card_btn">Ver Mais</button>
                                </div>
                            </a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>Não há animais para exibir </p>
        {% endif %}
    </div>
    
{% endblock %}

ongAdocao/adocao/templates/listaAnimais.html
{% extends 'base.html' %}

{% block bloco %}
    {% if animais %}
        <h1>Animais para Adoção</h1>
        <table class="table table-responsive-sm table-striped table-bordered table-sm" cellspacing="0"
        width="90%">
            <thead>
                <th>Foto</th>
                <th>Nome</th>
                <th>Sexo</th>
                <th>Porte</th>
            </thead>
            <tbody>
                {% for Animal in animais %}
                    <tr>
                        <th><img class="imagemAnimal" src="{{Animal.imagemAnimal.url}}"></th>
                        <th><p>{{Animal.nomeAnimal}}</p></th>
                        <th><p>{{Animal.get_sexo_display}}</p></th>
                        <th><p>{{Animal.get_porte_display}}</p></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h1>Não existem animais para adoção</h1>
    {% endif %}
    
{% endblock %}